Updates homepage of documentation
zendframework/zend-expressive pull request #671
Opened 2019-10-31 22:51 UTC by froschdesign

2019-11-02 11:45 UTC, michalbundyra requested changes

2019-11-02 11:45 UTC, michalbundyra commented on docs/book/index.md
> +ServerRequestInterface $request,
missing indent for function arguments

2019-11-02 11:45 UTC, michalbundyra commented on mkdocs.yml
>  copyright: 'Copyright (c) 2015-2018 <a href="https://www.zend.com/">Zend Technologies USA Inc.</a>'
we can remove above line

2019-11-02 12:29 UTC, froschdesign commented on docs/book/index.md
> +ServerRequestInterface $request,
Good catch!

2019-11-03 09:53 UTC, michalbundyra commented
Thanks, @froschdesign!

2019-11-03 09:53 UTC, merged

2019-11-03 09:53 UTC, michalbundyra approved these changes